### ISSUE TITLE
localhost:8080/JavaReact/assets/app.css Not Found

### ISSUE THREAD

**Issue by jkleiser** [emmostrom/JavaReact#1]
When running this project (mvn jetty:run), I see in my browser console that request are made for assets/app.css, and that results in 404.
In the pom.xml I'm using
```
<nodeVersion>v9.3.0</nodeVersion>
<npmVersion>5.6.0</npmVersion>
```
Can that cause this 404?

**Comment by emmostrom** [comment]
that's expected.  when running in development using jetty the css is hot-reloaded using the webpack dev server so there is no app.css file generated.  when building the war for production there is no hot-reloading so the css file is generated.
